name = "play-jonny-casino-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=play-jonny-casino.es"
HMAC_KEY = "531a38b48b6ec142ee4a3d65a421f0d794cf646159b38525dccd7cdcfe29973b"
COOKIE_NAME = "g4s"
PLAY_PATH = "start"
BUTTON_ID = "p156898b8e4dd400e988b4eec468b447f"
GATE_SALT = "cb330960101e285e"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0ytl"
CTA_SELECTOR = ".play-button"
